//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLDiem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiTap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BaiTap()
        {
            this.BaiTap_HocVien = new HashSet<BaiTap_HocVien>();
            this.BaiTapTepDinhKems = new HashSet<BaiTapTepDinhKem>();
            this.BaiTap_NhanXet = new HashSet<BaiTap_NhanXet>();
        }
    
        public int MaBaiTap { get; set; }
        public string TenBaiTap { get; set; }
        public string MoTa { get; set; }
        public int ThangDiem { get; set; }
        public int MaLopHoc { get; set; }
        public System.DateTime NgayBatDau { get; set; }
        public System.DateTime NgayKetThuc { get; set; }
        public int NguoiTao { get; set; }
        public Nullable<int> MaChuDe { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public int ThangDiemChuyenCan { get; set; }
    
        public virtual ChuDe ChuDe { get; set; }
        public virtual LopHoc LopHoc { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaiTap_HocVien> BaiTap_HocVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaiTapTepDinhKem> BaiTapTepDinhKems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaiTap_NhanXet> BaiTap_NhanXet { get; set; }
    }
}
