//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLDiem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiTap_HocVien
    {
        public int MaBaiTap { get; set; }
        public int MaHocVien { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public Nullable<System.DateTime> NgayGiao { get; set; }
        public Nullable<System.DateTime> NgayNop { get; set; }
        public Nullable<System.DateTime> NgayChamDiem { get; set; }
        public Nullable<int> DiemHocTap { get; set; }
        public Nullable<int> DiemChuyenCan { get; set; }
        public string NhanXetGiangVien { get; set; }
        public string TepDinhKem { get; set; }
        public string NoiDungGuiBai { get; set; }
    
        public virtual BaiTap BaiTap { get; set; }
        public virtual HocVien HocVien { get; set; }
    }
}
