//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLDiem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebQLDiemEntities : DbContext
    {
        public WebQLDiemEntities()
            : base("name=WebQLDiemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BaiTap> BaiTaps { get; set; }
        public virtual DbSet<BaiTap_HocVien> BaiTap_HocVien { get; set; }
        public virtual DbSet<BaiTap_NhanXet> BaiTap_NhanXet { get; set; }
        public virtual DbSet<BaiTapTepDinhKem> BaiTapTepDinhKems { get; set; }
        public virtual DbSet<ChuDe> ChuDes { get; set; }
        public virtual DbSet<GiangVien> GiangViens { get; set; }
        public virtual DbSet<HocVien> HocViens { get; set; }
        public virtual DbSet<LopHoc> LopHocs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
        public virtual DbSet<TaiKhoan_ThongBao> TaiKhoan_ThongBao { get; set; }
        public virtual DbSet<TaiLieu> TaiLieux { get; set; }
        public virtual DbSet<TaiLieu_NhanXet> TaiLieu_NhanXet { get; set; }
        public virtual DbSet<TaiLieuTepDinhKem> TaiLieuTepDinhKems { get; set; }
        public virtual DbSet<ThongBao> ThongBaos { get; set; }
        public virtual DbSet<ThongBao_NhanXet> ThongBao_NhanXet { get; set; }
        public virtual DbSet<ThongBaoTepDinhKem> ThongBaoTepDinhKems { get; set; }
    }
}
