//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLDiem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiLieu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaiLieu()
        {
            this.TaiLieu_NhanXet = new HashSet<TaiLieu_NhanXet>();
            this.TaiLieuTepDinhKems = new HashSet<TaiLieuTepDinhKem>();
            this.HocViens = new HashSet<HocVien>();
        }
    
        public int MaTaiLieu { get; set; }
        public Nullable<int> MaLopHoc { get; set; }
        public string TenTaiLieu { get; set; }
        public string MoTa { get; set; }
        public System.DateTime NgayTao { get; set; }
        public int NguoiTao { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public Nullable<int> MaChuDe { get; set; }
    
        public virtual ChuDe ChuDe { get; set; }
        public virtual LopHoc LopHoc { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaiLieu_NhanXet> TaiLieu_NhanXet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaiLieuTepDinhKem> TaiLieuTepDinhKems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HocVien> HocViens { get; set; }
    }
}
