//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLDiem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiLieuTepDinhKem
    {
        public int MaTepDinhKem { get; set; }
        public Nullable<int> MaTaiLieu { get; set; }
        public string DuongDan { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<int> NguoiTao { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
        public virtual TaiLieu TaiLieu { get; set; }
    }
}
